import { Client } from '../models/client.model';

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'cli_1',
    firstName: 'Carlos',
    lastName: 'Mendoza',
    phone: '+1 201-555-0123',
    email: 'carlos.mendoza@email.com',
    birthDate: '1985-05-14',
    address: '452 Broad St',
    city: 'Newark',
    state: 'NJ',
    zipCode: '07102',
    country: 'EE.UU.',
    preferredLanguage: 'Español',
    status: 'active',
    source: 'referral',
    assignedServices: ['srv_6', 'srv_11'], // Preparación de Impuestos, Seguro de Vida
    priority: 'high',
    assignedAgent: 'María Delgado',
    notes: 'Cliente muy puntual. Declara impuestos personales en conjunto con su cónyuge. Interesado en ampliar cobertura de seguro de vida para su hijo.',
    createdAt: '2026-01-12T10:30:00Z',
    updatedAt: '2026-03-05T11:20:00Z'
  },
  {
    id: 'cli_2',
    firstName: 'Diana',
    lastName: 'Rodríguez',
    phone: '+1 201-555-0456',
    email: 'diana.rod@email.com',
    birthDate: '1990-09-22',
    address: '128 Bergenline Ave',
    city: 'Union City',
    state: 'NJ',
    zipCode: '07087',
    country: 'EE.UU.',
    preferredLanguage: 'Español',
    status: 'in_progress',
    source: 'whatsapp',
    assignedServices: ['srv_2', 'srv_3'], // Trámites Migratorios, Visa EE.UU.
    priority: 'medium',
    assignedAgent: 'María Delgado',
    notes: 'Proceso de petición familiar para sus padres. Documentos de patrocinio en revisión.',
    createdAt: '2026-02-18T14:15:00Z',
    updatedAt: '2026-03-10T16:45:00Z'
  },
  {
    id: 'cli_3',
    firstName: 'John',
    lastName: 'Smith',
    phone: '+1 201-555-0789',
    email: 'john.smith@corporate.com',
    birthDate: '1978-12-05',
    address: '101 Hudson St, Suite 2100',
    city: 'Jersey City',
    state: 'NJ',
    zipCode: '07302',
    country: 'EE.UU.',
    preferredLanguage: 'Inglés',
    status: 'active',
    source: 'website',
    assignedServices: ['srv_5', 'srv_9'], // Contabilidad, Asesoría Empresarial
    priority: 'high',
    assignedAgent: 'Alejandro Ruiz',
    notes: 'Dueño de una pequeña distribuidora de alimentos. Lleva contabilidad mensual de su negocio LLC.',
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: '2026-03-01T09:00:00Z'
  },
  {
    id: 'cli_4',
    firstName: 'Sofia',
    lastName: 'Alvarado',
    phone: '+1 973-555-9876',
    email: 'sofia.alv@email.com',
    birthDate: '1995-03-30',
    address: '12 Market St',
    city: 'Paterson',
    state: 'NJ',
    zipCode: '07501',
    country: 'EE.UU.',
    preferredLanguage: 'Español',
    status: 'prospect',
    source: 'social_media',
    assignedServices: ['srv_8'], // Reparación de Crédito
    priority: 'low',
    assignedAgent: 'Alejandro Ruiz',
    notes: 'Consultó por Instagram interesada en reparar su crédito para poder calificar para una hipoteca de casa a finales de año.',
    createdAt: '2026-03-02T11:40:00Z',
    updatedAt: '2026-03-02T11:40:00Z'
  },
  {
    id: 'cli_5',
    firstName: 'Manuel',
    lastName: 'García',
    phone: '+1 201-555-1221',
    email: 'm.garcia.biz@email.com',
    birthDate: '1962-07-19',
    address: '88 Summit Ave',
    city: 'Jersey City',
    state: 'NJ',
    zipCode: '07306',
    country: 'EE.UU.',
    preferredLanguage: 'Español',
    status: 'active',
    source: 'office',
    assignedServices: ['srv_12', 'srv_21'], // Medicare, Anualidades Indexadas
    priority: 'high',
    assignedAgent: 'Sandra Gómez',
    notes: 'Cumplió 65 años recientemente. Se le ayudó a afiliarse en Medicare Parte A y B y se transfirió una suma importante a una Anualidad Indexada.',
    createdAt: '2026-01-15T15:20:00Z',
    updatedAt: '2026-02-28T10:15:00Z'
  },
  {
    id: 'cli_6',
    firstName: 'Elizabeth',
    lastName: 'Castro',
    phone: '+1 908-555-3344',
    email: 'elizabeth.c@email.com',
    birthDate: '1989-11-02',
    address: '320 Elmora Ave',
    city: 'Elizabeth',
    state: 'NJ',
    zipCode: '07202',
    country: 'EE.UU.',
    preferredLanguage: 'Español',
    status: 'inactive',
    source: 'call',
    assignedServices: ['srv_13'], // Seguro de Carro
    priority: 'low',
    assignedAgent: 'Sandra Gómez',
    notes: 'Canceló póliza de auto por mudanza a otro estado. Dejó abierta la posibilidad de retornar servicios si regresa a NJ.',
    createdAt: '2026-01-08T13:00:00Z',
    updatedAt: '2026-02-15T17:00:00Z'
  },
  {
    id: 'cli_7',
    firstName: 'Ricardo',
    lastName: 'Palacios',
    phone: '+1 201-555-5566',
    email: 'rpalacios@email.com',
    birthDate: '1973-02-25',
    address: '77 Ocean Ave',
    city: 'Jersey City',
    state: 'NJ',
    zipCode: '07305',
    country: 'EE.UU.',
    preferredLanguage: 'Español',
    status: 'prospect',
    source: 'referral',
    assignedServices: ['srv_20'], // Proyectos Inmobiliarios (Real Estate)
    priority: 'medium',
    assignedAgent: 'Alejandro Ruiz',
    notes: 'Referido de John Smith. Interesado en invertir en un apartamento de 2 habitaciones en Jersey City. Aún sin pre-aprobación bancaria.',
    createdAt: '2026-03-08T09:15:00Z',
    updatedAt: '2026-03-08T09:15:00Z'
  },
  {
    id: 'cli_8',
    firstName: 'Valeria',
    lastName: 'Ortiz',
    phone: '+1 551-555-8899',
    email: 'valeria.ortiz@email.com',
    birthDate: '1992-08-08',
    address: '512 Anderson Ave',
    city: 'Cliffside Park',
    state: 'NJ',
    zipCode: '07010',
    country: 'EE.UU.',
    preferredLanguage: 'Español',
    status: 'closed',
    source: 'whatsapp',
    assignedServices: ['srv_4'], // Oficiante de Bodas
    priority: 'medium',
    assignedAgent: 'María Delgado',
    notes: 'Boda realizada con éxito el 14 de febrero de 2026 en Edgewater. Licencia de matrimonio procesada e inscrita.',
    createdAt: '2026-02-06T10:00:00Z',
    updatedAt: '2026-02-16T11:00:00Z'
  }
];
