import { Property } from '../models/property.model';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop_1',
    name: 'Condominio Hudson View',
    type: 'apartment',
    address: '745 River Rd, Apt 4B',
    city: 'Edgewater',
    state: 'NJ',
    zipCode: '07020',
    country: 'USA',
    description: 'Hermoso apartamento de lujo con vista panorámica a la ciudad de Nueva York y al río Hudson. Acabados premium, cocina de diseñador, balcón privado y amenidades completas de edificio (gimnasio, piscina, conserjería 24/7).',
    currentPrice: 620000,
    previousPrice: 645000,
    status: 'available',
    operationType: 'sale',
    bedrooms: 2,
    bathrooms: 2,
    area: 1250, // sq ft
    lotSize: 0,
    yearBuilt: 2018,
    ownerName: 'Roberto Valenzuela',
    ownerPhone: '+1 201-555-9011',
    ownerEmail: 'robertov@email.com',
    agent: 'Alejandro Ruiz',
    estimatedCommission: 18600, // 3% commission
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=600&q=80',
    notes: 'El dueño está dispuesto a negociar el mobiliario. Mantenimiento mensual del HOA: $450.',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-03-02T15:30:00Z'
  },
  {
    id: 'prop_2',
    name: 'Casa Familiar Colonial',
    type: 'house',
    address: '215 Elm St',
    city: 'Teaneck',
    state: 'NJ',
    zipCode: '07666',
    country: 'USA',
    description: 'Clásica casa estilo colonial en un barrio residencial tranquilo y arborizado. Cuenta con un amplio patio trasero, sótano terminado, chimenea a leña y cochera para dos autos. Excelente distrito escolar cercano.',
    currentPrice: 485000,
    status: 'available',
    operationType: 'sale',
    bedrooms: 4,
    bathrooms: 2.5,
    area: 2100,
    lotSize: 6500, // sq ft
    yearBuilt: 1965,
    ownerName: 'Katherine Miller',
    ownerPhone: '+1 201-555-8822',
    ownerEmail: 'k.miller@email.com',
    agent: 'Sandra Gómez',
    estimatedCommission: 14550,
    imageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=600&q=80',
    notes: 'Requiere actualizaciones cosméticas en los baños. Calefacción central a gas natural.',
    createdAt: '2026-02-10T11:30:00Z',
    updatedAt: '2026-02-10T11:30:00Z'
  },
  {
    id: 'prop_3',
    name: 'Townhouse en Bergen Line',
    type: 'multifamily',
    address: '4201 Hudson Ave',
    city: 'Union City',
    state: 'NJ',
    zipCode: '07087',
    country: 'USA',
    description: 'Propiedad multifamiliar de dos unidades independiente (duplex), ideal para inversión de renta. Unidad 1 con 2 hab y 1 baño. Unidad 2 con 3 hab y 2 baños. Excelente ubicación con transporte directo a Manhattan en la esquina.',
    currentPrice: 750000,
    previousPrice: 780000,
    status: 'reserved',
    operationType: 'investment',
    bedrooms: 5,
    bathrooms: 3,
    area: 2800,
    lotSize: 2500,
    yearBuilt: 1920,
    ownerName: 'Inversiones del Norte LLC',
    ownerPhone: '+1 973-555-0011',
    agent: 'Alejandro Ruiz',
    estimatedCommission: 22500,
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=600&q=80',
    notes: 'Actualmente ambas unidades están rentadas con contratos mes a mes generando un ingreso bruto mensual de $4,800. Posible aumento de rentas tras renovación.',
    createdAt: '2026-01-20T09:15:00Z',
    updatedAt: '2026-03-12T10:00:00Z'
  },
  {
    id: 'prop_4',
    name: 'Apartamento Vista al Parque',
    type: 'apartment',
    address: '120 Wood Ave, Apt 12C',
    city: 'Linden',
    state: 'NJ',
    zipCode: '07036',
    country: 'USA',
    description: 'Moderno apartamento tipo estudio loft en un complejo recientemente construido. Concepto abierto, aire acondicionado central, electrodomésticos de acero inoxidable y lavadora/secadora dentro del apartamento.',
    currentPrice: 2100,
    status: 'rented',
    operationType: 'rent',
    bedrooms: 1,
    bathrooms: 1,
    area: 720,
    lotSize: 0,
    yearBuilt: 2022,
    ownerName: 'James Chen',
    ownerPhone: '+1 908-555-1234',
    ownerEmail: 'j.chen@gmail.com',
    agent: 'Sandra Gómez',
    estimatedCommission: 2100, // 1 month of rent as commission
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=600&q=80',
    notes: 'Contrato firmado por 12 meses iniciado el 1 de marzo de 2026.',
    createdAt: '2026-02-01T14:00:00Z',
    updatedAt: '2026-03-01T12:00:00Z'
  },
  {
    id: 'prop_5',
    name: 'Edificio Comercial Broad St',
    type: 'commercial',
    address: '810 Broad St',
    city: 'Newark',
    state: 'NJ',
    zipCode: '07102',
    country: 'USA',
    description: 'Local comercial a nivel de calle con excelente visibilidad y alto tráfico peatonal en pleno centro de Newark. 2 pisos con espacio para oficinas, salas de juntas y área de retail. Estacionamiento privado trasero para 6 autos.',
    currentPrice: 1350000,
    status: 'available',
    operationType: 'sale',
    bedrooms: 0,
    bathrooms: 4,
    area: 5200,
    lotSize: 7500,
    yearBuilt: 1980,
    ownerName: 'Newark Holdings LLC',
    ownerPhone: '+1 973-555-4433',
    agent: 'Alejandro Ruiz',
    estimatedCommission: 40500,
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80',
    notes: 'Listo para ocuparse. Estructura de concreto sólida, sistemas de aire acondicionado zonificados recién reemplazados.',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-02-28T09:00:00Z'
  }
];
