import { Service } from '../models/service.model';

export const MOCK_SERVICES: Service[] = [
  // Trámites y Notaría
  {
    id: 'srv_1',
    name: 'Notaría Pública',
    category: 'Trámites y Notaría',
    description: 'Servicios de notarización de todo tipo de documentos legales, actas, cartas de poder y declaraciones juradas.',
    estimatedPrice: 50,
    status: 'active',
    estimatedDuration: '15-30 minutos',
    requiredDocuments: ['Identificación oficial vigente', 'Documento a notarizar original'],
    notes: 'Tarifa básica por documento. Firmas adicionales tienen costo extra.',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z'
  },
  {
    id: 'srv_2',
    name: 'Trámites Migratorios',
    category: 'Trámites y Notaría',
    description: 'Asesoría y acompañamiento en solicitudes de residencia, peticiones familiares y ciudadanía estadounidense.',
    estimatedPrice: 850,
    status: 'active',
    estimatedDuration: '3-12 meses',
    requiredDocuments: ['Pasaporte', 'Acta de nacimiento traducida', 'Pruebas de relación familiar', 'Historial migratorio'],
    notes: 'No incluye tarifas del servicio de inmigración (USCIS).',
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-02-20T14:00:00Z'
  },
  {
    id: 'srv_3',
    name: 'Aplicaciones de Visa para Estados Unidos',
    category: 'Trámites y Notaría',
    description: 'Preparación de formularios DS-160, programación de citas en la embajada y asesoría para entrevista consular.',
    estimatedPrice: 200,
    status: 'active',
    estimatedDuration: '1-3 meses',
    requiredDocuments: ['Pasaporte vigente', 'Fotografía digital tamaño visa', 'Información de empleo y solvencia económica'],
    notes: 'Soporte completo desde el llenado de formularios hasta la preparación para la entrevista.',
    createdAt: '2026-01-20T11:00:00Z',
    updatedAt: '2026-01-20T11:00:00Z'
  },
  {
    id: 'srv_4',
    name: 'Oficiante de Bodas en New Jersey',
    category: 'Trámites y Notaría',
    description: 'Ceremonias de matrimonio civil legales y personalizadas en el estado de New Jersey, registro de licencia matrimonial.',
    estimatedPrice: 350,
    status: 'active',
    estimatedDuration: '1-2 horas',
    requiredDocuments: ['Licencia de matrimonio del estado de New Jersey', 'Identificación de dos testigos'],
    notes: 'Es necesario solicitar la licencia de matrimonio con al menos 72 horas de anticipación en el municipio correspondiente.',
    createdAt: '2026-02-05T16:00:00Z',
    updatedAt: '2026-02-05T16:00:00Z'
  },

  // Contabilidad y Finanzas
  {
    id: 'srv_5',
    name: 'Contabilidad y Finanzas',
    category: 'Contabilidad y Finanzas',
    description: 'Bookkeeping mensual, conciliación bancaria y estados financieros para pequeños y medianos negocios.',
    estimatedPrice: 250,
    status: 'active',
    estimatedDuration: 'Mensual',
    requiredDocuments: ['Estados de cuenta bancarios', 'Facturas emitidas y recibidas', 'Reportes de ventas'],
    notes: 'El costo varía según el volumen de transacciones mensuales del negocio.',
    createdAt: '2026-01-05T08:00:00Z',
    updatedAt: '2026-01-05T08:00:00Z'
  },
  {
    id: 'srv_6',
    name: 'Preparación de Impuestos',
    category: 'Contabilidad y Finanzas',
    description: 'Declaración de impuestos personales (1040) y corporativos (1120/1120S/1065) a nivel federal y estatal.',
    estimatedPrice: 150,
    status: 'active',
    estimatedDuration: '1-3 días',
    requiredDocuments: ['W-2 / 1099', 'Declaración del año anterior', 'Identificación y número de Seguro Social o ITIN'],
    notes: 'Precios desde $150 para declaraciones sencillas.',
    createdAt: '2026-01-05T08:30:00Z',
    updatedAt: '2026-03-01T10:00:00Z'
  },
  {
    id: 'srv_7',
    name: 'Creación de Patrimonio',
    category: 'Contabilidad y Finanzas',
    description: 'Asesoría y diseño de planes financieros estructurados para acumulación de activos, protección familiar y ahorro a largo plazo.',
    estimatedPrice: 500,
    status: 'active',
    estimatedDuration: '2-4 semanas',
    requiredDocuments: ['Reporte de ingresos', 'Detalle de activos y pasivos actuales'],
    notes: 'Plan personalizado con revisión semestral.',
    createdAt: '2026-02-10T12:00:00Z',
    updatedAt: '2026-02-10T12:00:00Z'
  },
  {
    id: 'srv_8',
    name: 'Reparación de Crédito',
    category: 'Contabilidad y Finanzas',
    description: 'Análisis de reporte de crédito, envío de cartas de disputa a burós de crédito e incremento de score crediticio.',
    estimatedPrice: 99,
    status: 'active',
    estimatedDuration: '3-6 meses',
    requiredDocuments: ['Reporte de crédito de las 3 agencias principales', 'Identificación oficial', 'Comprobante de domicilio'],
    notes: 'Mensualidad fija de $99. No se cobra tarifa por adelantado por el trabajo que no se ha realizado.',
    createdAt: '2026-02-12T14:30:00Z',
    updatedAt: '2026-02-12T14:30:00Z'
  },
  {
    id: 'srv_9',
    name: 'Asesoría Empresarial',
    category: 'Contabilidad y Finanzas',
    description: 'Consultoría integral para apertura de LLC, corporaciones C/S, estructuración corporativa y licencias de operación.',
    estimatedPrice: 300,
    status: 'active',
    estimatedDuration: '1-2 semanas',
    requiredDocuments: ['Nombre propuesto', 'Identificación de los socios', 'Dirección física del negocio'],
    notes: 'No incluye las tasas estatales de registro de corporación.',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-02-15T10:00:00Z'
  },

  // Seguros
  {
    id: 'srv_10',
    name: 'Seguros de Salud',
    category: 'Seguros',
    description: 'Planes de salud privados, familiares y del mercado de salud (Obamacare) para cobertura médica integral.',
    estimatedPrice: 0,
    status: 'active',
    estimatedDuration: '1-5 días',
    requiredDocuments: ['Comprobante de ingresos (W2/1099/Tax Return)', 'Seguro Social/Estatus migratorio legal'],
    notes: 'Muchas personas califican para subsidios del gobierno reduciendo la prima mensual a $0.',
    createdAt: '2026-01-02T15:00:00Z',
    updatedAt: '2026-01-02T15:00:00Z'
  },
  {
    id: 'srv_11',
    name: 'Seguros de Vida',
    category: 'Seguros',
    description: 'Seguros de vida a término, permanente o con beneficios en vida para protección económica de tus beneficiarios.',
    estimatedPrice: 45,
    status: 'active',
    estimatedDuration: '1-2 semanas',
    requiredDocuments: ['Identificación', 'Cuestionario médico simplificado'],
    notes: 'Cotización sujeta a edad, salud y monto de cobertura solicitado.',
    createdAt: '2026-01-02T15:30:00Z',
    updatedAt: '2026-01-02T15:30:00Z'
  },
  {
    id: 'srv_12',
    name: 'Medicare',
    category: 'Seguros',
    description: 'Asesoría y afiliación en planes Medicare Advantage (Parte C), Suplementarios (Medigap) y recetas médicas (Parte D).',
    estimatedPrice: 0,
    status: 'active',
    estimatedDuration: '2-5 días',
    requiredDocuments: ['Tarjeta de Medicare Parte A y B'],
    notes: 'Para mayores de 65 años o personas con discapacidades elegibles.',
    createdAt: '2026-01-12T11:00:00Z',
    updatedAt: '2026-01-12T11:00:00Z'
  },
  {
    id: 'srv_13',
    name: 'Seguros de Carro',
    category: 'Seguros',
    description: 'Cotización y emisión de pólizas de auto con cobertura de responsabilidad civil o cobertura total.',
    estimatedPrice: 120,
    status: 'active',
    estimatedDuration: '1 hora',
    requiredDocuments: ['Licencia de conducir', 'Título o registro de vehículo', 'Historial de manejo'],
    notes: 'Trabajamos con múltiples aseguradoras para buscar la tarifa más económica.',
    createdAt: '2026-01-02T16:00:00Z',
    updatedAt: '2026-01-02T16:00:00Z'
  },
  {
    id: 'srv_14',
    name: 'Progressive',
    category: 'Seguros',
    description: 'Pólizas de seguro Progressive para automóviles, propiedades, botes y vehículos comerciales.',
    estimatedPrice: 110,
    status: 'active',
    estimatedDuration: '1 hora',
    requiredDocuments: ['Información del vehículo (VIN)', 'Datos de conductores'],
    notes: 'Representante autorizado Progressive.',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-01-15T09:00:00Z'
  },
  {
    id: 'srv_15',
    name: 'GEICO',
    category: 'Seguros',
    description: 'Emisión y ajuste de pólizas de auto y hogar a través de GEICO con descuentos especiales.',
    estimatedPrice: 95,
    status: 'active',
    estimatedDuration: '1 hora',
    requiredDocuments: ['Información del vehículo (VIN)', 'Detalles de póliza anterior'],
    notes: 'Soporte en español para clientes GEICO.',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z'
  },
  {
    id: 'srv_16',
    name: 'Seguros de Compañía',
    category: 'Seguros',
    description: 'Seguro de responsabilidad civil general (General Liability) y Workers Compensation para contratistas y empresas.',
    estimatedPrice: 150,
    status: 'active',
    estimatedDuration: '2-5 días',
    requiredDocuments: ['Información de nómina', 'Detalle de actividades comerciales', 'EIN de la empresa'],
    notes: 'Crucial para cumplir con requisitos legales en contratos comerciales.',
    createdAt: '2026-01-22T14:00:00Z',
    updatedAt: '2026-01-22T14:00:00Z'
  },
  {
    id: 'srv_17',
    name: 'ETHOS',
    category: 'Seguros',
    description: 'Seguro de vida de emisión rápida simplificada ETHOS, sin exámenes médicos en la mayoría de los casos.',
    estimatedPrice: 30,
    status: 'active',
    estimatedDuration: '24 horas',
    requiredDocuments: ['Datos de salud básicos', 'Información de beneficiarios'],
    notes: 'Aprobación casi inmediata a través de plataforma web.',
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-02-01T09:00:00Z'
  },
  {
    id: 'srv_18',
    name: 'Corebridge',
    category: 'Seguros',
    description: 'Soluciones de seguros de vida y planes de retiro Corebridge Financial para seguridad a largo plazo.',
    estimatedPrice: 80,
    status: 'active',
    estimatedDuration: '2-3 semanas',
    requiredDocuments: ['Identificación', 'Examen físico opcional', 'Datos de beneficiarios'],
    notes: 'Excelente para pólizas de acumulación con valor en efectivo.',
    createdAt: '2026-02-18T10:30:00Z',
    updatedAt: '2026-02-18T10:30:00Z'
  },
  {
    id: 'srv_19',
    name: 'AuguStar',
    category: 'Seguros',
    description: 'Seguros de vida AuguStar y soluciones de inversión garantizada para protección y retiro.',
    estimatedPrice: 70,
    status: 'active',
    estimatedDuration: '2-3 semanas',
    requiredDocuments: ['Identificación', 'Formulario médico'],
    notes: 'Planes flexibles con diversas opciones de inversión.',
    createdAt: '2026-02-20T11:00:00Z',
    updatedAt: '2026-02-20T11:00:00Z'
  },

  // Real Estate
  {
    id: 'srv_20',
    name: 'Proyectos Inmobiliarios',
    category: 'Real Estate',
    description: 'Asesoría en compra, venta y estructuración financiera para desarrollo de proyectos inmobiliarios residenciales o comerciales.',
    estimatedPrice: 1500,
    status: 'active',
    estimatedDuration: 'Variable',
    requiredDocuments: ['Estados financieros', 'Identificaciones', 'Pre-aprobación de hipoteca si aplica'],
    notes: 'Servicio premium de consultoría y corretaje.',
    createdAt: '2026-01-08T09:00:00Z',
    updatedAt: '2026-01-08T09:00:00Z'
  },

  // Retiro y Jubilación
  {
    id: 'srv_21',
    name: 'Anualidades Indexadas',
    category: 'Retiro y Jubilación',
    description: 'Planes de anualidades fijas indexadas (FIA) que protegen tu capital del mercado de valores y brindan ingresos garantizados de por vida.',
    estimatedPrice: 0,
    status: 'active',
    estimatedDuration: '2-3 semanas',
    requiredDocuments: ['Identificación', 'Declaraciones de cuentas financieras actuales (de ser transferencia)'],
    notes: 'Las anualidades protegen contra pérdidas en el mercado mientras capturan parte de las alzas.',
    createdAt: '2026-01-25T15:00:00Z',
    updatedAt: '2026-01-25T15:00:00Z'
  },
  {
    id: 'srv_22',
    name: '401(k) o 403(b)',
    category: 'Retiro y Jubilación',
    description: 'Asesoría para el establecimiento o revisión de planes de retiro corporativos o individuales para maximizar contribuciones libres de impuestos.',
    estimatedPrice: 200,
    status: 'active',
    estimatedDuration: '2 semanas',
    requiredDocuments: ['Información fiscal', 'Detalles de nómina de la empresa'],
    notes: 'Ayuda a las empresas a implementar incentivos de ahorro para empleados.',
    createdAt: '2026-01-25T15:30:00Z',
    updatedAt: '2026-01-25T15:30:00Z'
  },
  {
    id: 'srv_23',
    name: 'IRA Rollover',
    category: 'Retiro y Jubilación',
    description: 'Transferencia de fondos de antiguos planes 401(k) de empleadores anteriores hacia una cuenta IRA tradicional o Roth sin penalidades fiscales.',
    estimatedPrice: 150,
    status: 'active',
    estimatedDuration: '1-2 semanas',
    requiredDocuments: ['Estado de cuenta del 401(k) anterior', 'Identificación oficial'],
    notes: 'Evita penalidades por retiro temprano consolidando el dinero en un IRA.',
    createdAt: '2026-01-26T10:00:00Z',
    updatedAt: '2026-01-26T10:00:00Z'
  },
  {
    id: 'srv_24',
    name: 'Cobertura Gastos Finales',
    category: 'Retiro y Jubilación',
    description: 'Seguro de vida de aceptación simplificada diseñado para cubrir costos de funeral y servicios fúnebres de manera que no afecte a la familia.',
    estimatedPrice: 50,
    status: 'active',
    estimatedDuration: '1-3 días',
    requiredDocuments: ['Identificación del asegurado y beneficiarios'],
    notes: 'Especialmente recomendado para adultos mayores.',
    createdAt: '2026-01-28T14:00:00Z',
    updatedAt: '2026-01-28T14:00:00Z'
  },
  {
    id: 'srv_25',
    name: 'Pensiones Privadas',
    category: 'Retiro y Jubilación',
    description: 'Diseño e implementación de sistemas de jubilación privada individual suplementaria para garantizar flujos constantes en edad de retiro.',
    estimatedPrice: 300,
    status: 'active',
    estimatedDuration: '2-3 semanas',
    requiredDocuments: ['Cálculo de ingresos proyectados', 'Estatus migratorio'],
    notes: 'Excelente para contratistas independientes o personas sin pensión de gobierno.',
    createdAt: '2026-02-02T11:00:00Z',
    updatedAt: '2026-02-02T11:00:00Z'
  },
  {
    id: 'srv_26',
    name: 'Fondos Universidad',
    category: 'Retiro y Jubilación',
    description: 'Planes de ahorro educativos estructurados (como planes 529 o seguros de valor efectivo acumulado) para la futura educación superior de tus hijos.',
    estimatedPrice: 100,
    status: 'active',
    estimatedDuration: '1 semana',
    requiredDocuments: ['Identificación de los padres', 'Seguro Social/ITIN del menor'],
    notes: 'Ahorro con beneficios fiscales enfocado a estudios universitarios.',
    createdAt: '2026-02-08T15:30:00Z',
    updatedAt: '2026-02-08T15:30:00Z'
  }
];
